name: Blogdown
version: 0.2.4
author: Alex Becker
maintainer: acbecker@uchicago.edu
license: AGPL-3

extra-source-files:
  - ChangeLog.md
  - Readme.md
  - goldens/*.md
data-files:
  - assets/Footnotes.css
  - assets/Footnotes.js

dependencies:
  - base >=4.9 && <5

library:
  source-dirs:
    - src
    - assets
  dependencies:
    - parsec >=3.1 && <3.2
    - containers >=0.5 && <0.7
    - MissingH >=1.4 && <1.7
    - network-uri >=2.6 && <2.8

executables:
  Blogdown:
    main: Blogdown.hs
    source-dirs:
      - app
      - src
      - assets
    dependencies:
      - Blogdown
      - parsec >=3.1 && <3.2
      - containers >=0.5 && <0.7
      - MissingH >=1.4 && <1.7
      - network-uri >=2.6 && <2.8

tests:
  Test:
    main: Test.hs
    source-dirs:
      - test
      - src
      - assets
    dependencies:
      - Blogdown
      - parsec >=3.1 && <3.2
      - containers >=0.5 && <0.7
      - MissingH >=1.4 && <1.7
      - network-uri >=2.6 && <2.8

benchmarks:
  Benchmark:
    main: Benchmark.hs
    source-dirs:
      - test
      - src
      - assets
    dependencies:
      - Blogdown
      - parsec >=3.1 && <3.2
      - containers >=0.5 && <0.7
      - MissingH >=1.4 && <1.7
      - criterion >=1.1 && <1.2
      - network-uri >=2.6 && <2.8
